apiVersion: v1
kind: Service
metadata:
  name: api-gateway-grupo1-service
  labels:
    app: api-gateway-grupo1
    grupo: grupo1
spec:
  type: ClusterIP
  selector:
    app: api-gateway-grupo1
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
