apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  labels:
    app: api-gateway
type: Opaque
stringData:
  # IMPORTANTE: Este secret DEBE ser el MISMO que usa el users-service
  JWT_SECRET: "supersecret-change-me"
